Make kind-generics-th's tests compile on GHC 8.10
Due to GHC commit
https://gitlab.haskell.org/ghc/ghc/commit/9612e91c793830b3049d2bc9a9ee28d9d82b928d,
GHC's constraint solver now solves contraints for each top-level
group sooner. A consequence is that TH splices strictly separate
top-level groups, which causes `kind-generics-th`'s test suite to
fail to compile on GHC 8.10:

```
tests/Main.hs:82:17: error:
    • No instance for (GenericK TC4) arising from a use of ‘isGenericK’
    • In the expression: isGenericK @_ @TC4 @(_ :&&: 'LoT0)
      In the expression:
        [isGenericK @_ @(V1 _) @'LoT0, isGenericK @_ @V1 @(_ :&&: 'LoT0),
         isGenericK @_ @((:+:) _ _ _) @'LoT0,
         isGenericK @_ @((:+:) _ _) @(_ :&&: 'LoT0), ....]
      In an equation for ‘insts’:
          insts
            = [isGenericK @_ @(V1 _) @'LoT0, isGenericK @_ @V1 @(_ :&&: 'LoT0),
               isGenericK @_ @((:+:) _ _ _) @'LoT0, ....]
   |
82 |               , isGenericK @_ @TC4     @(_ ':&&: 'LoT0)
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

tests/Main.hs:84:17: error:
    • No instance for (GenericK (TC5 _45))
        arising from a use of ‘isGenericK’
    • In the expression: isGenericK @_ @(TC5 _) @'LoT0
      In the expression:
        [isGenericK @_ @(V1 _) @'LoT0, isGenericK @_ @V1 @(_ :&&: 'LoT0),
         isGenericK @_ @((:+:) _ _ _) @'LoT0,
         isGenericK @_ @((:+:) _ _) @(_ :&&: 'LoT0), ....]
      In an equation for ‘insts’:
          insts
            = [isGenericK @_ @(V1 _) @'LoT0, isGenericK @_ @V1 @(_ :&&: 'LoT0),
               isGenericK @_ @((:+:) _ _ _) @'LoT0, ....]
   |
84 |               , isGenericK @_ @(TC5 _) @'LoT0
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

-- etc.
```

This patch fixes the issue by reordering some things in the test
suite to avoid ordering issues.